version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: "postgresql://postgres:IlHDCDdQAMbcLFAUqBMbaMsKoaoAryng@junction.proxy.rlwy.net:31347/railway"
      GEMINI_API_KEY: "AIzaSyAE_sK4m-U1GZ1tTAzBeltcf-rUG1hDw3A"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: IlHDCDdQAMbcLFAUqBMbaMsKoaoAryng
      POSTGRES_DB: railway
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network: