version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: "postgresql://postgres:BVIPQhoeQUjotJqXoTMdttxJEgNdFMiw@junction.proxy.rlwy.net:53398/railway"
      GEMINI_API_KEY: ""
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BVIPQhoeQUjotJqXoTMdttxJEgNdFMiw
      POSTGRES_DB: railway
    ports:
      - "53398:53398"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network: